-- ============================================================================
-- KIZK.jp フリースクール・通信制高校サポート校運営システム
-- 初期スキーマ（PHP+MySQL版からの移植: kizksaas2_ugo）
-- ============================================================================
-- 個人情報・秘密情報は一切含まない（構造のみ）。データはSupabase SQL Editorで
-- 別途 supabase/seed_local/ 配下のファイル（gitignore対象）から投入すること。

-- updated_at を自動更新する共通トリガー関数
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- ----------------------------------------------------------------------------
-- academies（学院＝テナント）
-- ----------------------------------------------------------------------------
create table academies (
  id              integer generated by default as identity primary key,
  code            varchar(50) not null unique,
  name            varchar(200) not null,
  address         varchar(300),
  phone           varchar(20),
  principal_name  varchar(100),
  contact_email   varchar(200),
  is_active       boolean not null default true,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create trigger trg_academies_updated_at before update on academies
  for each row execute function set_updated_at();

-- ----------------------------------------------------------------------------
-- admin_users（スタッフ・管理者プロフィール。認証自体はSupabase Authが担う）
-- ----------------------------------------------------------------------------
create table admin_users (
  id             integer generated by default as identity primary key,
  auth_user_id   uuid unique references auth.users(id) on delete set null,
  academy_id     integer references academies(id),
  username       varchar(50) not null unique,
  display_name   varchar(100) not null,
  role           varchar(10) not null default 'staff' check (role in ('super','staff')),
  is_kizk_admin  boolean not null default false,
  is_active      boolean not null default true,
  last_login     timestamptz,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create trigger trg_admin_users_updated_at before update on admin_users
  for each row execute function set_updated_at();

-- ----------------------------------------------------------------------------
-- schools（生徒の所属元学校）
-- ----------------------------------------------------------------------------
create table schools (
  id              integer generated by default as identity primary key,
  academy_id      integer not null default 1 references academies(id),
  department      varchar(10) not null default '小中等部' check (department in ('小中等部','高等部','両方')),
  name            varchar(200) not null,
  address         varchar(300),
  phone           varchar(20),
  principal_name  varchar(100),
  fax_number      varchar(20),
  email           varchar(200),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create trigger trg_schools_updated_at before update on schools
  for each row execute function set_updated_at();

-- ----------------------------------------------------------------------------
-- students（生徒）
-- ----------------------------------------------------------------------------
create table students (
  id                integer generated by default as identity primary key,
  academy_id        integer not null default 1 references academies(id),
  department        varchar(10) not null check (department in ('小中等部','高等部')),
  name              varchar(100) not null,
  name_kana         varchar(100),
  birth_date        date,
  gender            varchar(10) check (gender in ('男','女','その他')),
  school_id         integer references schools(id) on delete set null,
  guardian_name     varchar(100),
  guardian_phone    varchar(20),
  guardian_email    varchar(200),
  school_grade      varchar(20),
  school_class      varchar(20),
  homeroom_teacher  varchar(100),
  notes             text,
  mypage_token      char(32) unique,
  student_email     varchar(200),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create trigger trg_students_updated_at before update on students
  for each row execute function set_updated_at();

-- ----------------------------------------------------------------------------
-- attendance（出欠記録）
-- ----------------------------------------------------------------------------
create table attendance (
  id               integer generated by default as identity primary key,
  student_id       integer not null references students(id) on delete cascade,
  attendance_date  date not null,
  status           varchar(10) not null default 'present' check (status in ('present','absent')),
  memo             text,
  unique (student_id, attendance_date)
);

-- ----------------------------------------------------------------------------
-- calendar_events（休校日・行事カレンダー）
-- ----------------------------------------------------------------------------
create table calendar_events (
  id              integer generated by default as identity primary key,
  academy_id      integer not null default 1 references academies(id),
  -- 旧システムの移行不備で空文字が残っているレコードがあるため '' も許容
  source_type     varchar(10) not null default '学院' check (source_type in ('学院','学校','')),
  school_id       integer references schools(id) on delete cascade,
  event_date      date not null,
  end_date        date,
  title           varchar(200) not null,
  event_category  varchar(20) not null default 'その他'
                    check (event_category in ('休校日','行事','定期テスト','長期休暇','お知らせ','その他')),
  is_closed       boolean not null default false,
  memo            text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create trigger trg_calendar_events_updated_at before update on calendar_events
  for each row execute function set_updated_at();

-- ----------------------------------------------------------------------------
-- worksheet_files（教材ライブラリ）
-- ----------------------------------------------------------------------------
create table worksheet_files (
  id          integer generated by default as identity primary key,
  academy_id  integer references academies(id),
  department  varchar(10) not null default '小中等部' check (department in ('小中等部','高等部')),
  grade       varchar(20) not null,
  subject     varchar(50) not null,
  title       varchar(200) not null,
  file_path   varchar(300) not null,
  file_type   varchar(10) not null default 'pdf' check (file_type in ('pdf','image')),
  difficulty  varchar(5) not null default '普' check (difficulty in ('易','普','難')),
  page_count  integer not null default 1,
  memo        text,
  created_at  timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- assignments（課題割り当て）
-- ----------------------------------------------------------------------------
create table assignments (
  id             integer generated by default as identity primary key,
  student_id     integer not null references students(id) on delete cascade,
  worksheet_id   integer not null references worksheet_files(id) on delete cascade,
  assigned_date  date not null,
  problem_start  integer not null default 1,
  problem_end    integer not null default 10,
  status         varchar(10) not null default 'assigned' check (status in ('assigned','scored')),
  memo           text,
  created_at     timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- assignment_scores（採点記録）
-- ----------------------------------------------------------------------------
create table assignment_scores (
  id              integer generated by default as identity primary key,
  assignment_id   integer not null references assignments(id) on delete cascade,
  problem_number  integer not null,
  is_correct      boolean not null,
  scored_at       timestamptz default now(),
  unique (assignment_id, problem_number)
);

-- ----------------------------------------------------------------------------
-- student_subject_levels（生徒別科目レベル）
-- ----------------------------------------------------------------------------
create table student_subject_levels (
  id              integer generated by default as identity primary key,
  student_id      integer not null references students(id) on delete cascade,
  subject         varchar(50) not null,
  difficulty      varchar(5) not null default '普' check (difficulty in ('易','普','難')),
  daily_problems  integer not null default 10,
  unique (student_id, subject)
);

-- ----------------------------------------------------------------------------
-- weak_points（苦手記録）
-- ----------------------------------------------------------------------------
create table weak_points (
  id              integer generated by default as identity primary key,
  student_id      integer not null references students(id) on delete cascade,
  subject         varchar(50) not null,
  topic           varchar(100),
  assignment_id   integer references assignments(id) on delete set null,
  problem_number  integer,
  recorded_date   date not null,
  is_resolved     boolean not null default false,
  memo            text,
  created_at      timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- learning_progress（学習進捗記録）
-- ----------------------------------------------------------------------------
create table learning_progress (
  id            integer generated by default as identity primary key,
  student_id    integer not null references students(id) on delete cascade,
  progress_date date not null,
  subject       varchar(100),
  content       text not null,
  duration_min  integer,
  teacher_note  text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create trigger trg_learning_progress_updated_at before update on learning_progress
  for each row execute function set_updated_at();

-- ----------------------------------------------------------------------------
-- hs_reports（高校レポート：OCR・AI回答）
-- ----------------------------------------------------------------------------
create table hs_reports (
  id                integer generated by default as identity primary key,
  student_id        integer not null references students(id) on delete cascade,
  grade             varchar(20) not null,
  subject           varchar(100) not null,
  report_title      varchar(200),
  file_path         varchar(300) not null,
  file_type         varchar(10) not null default 'image' check (file_type in ('pdf','image')),
  ocr_text          text,
  ai_answer         text,
  ai_processed_at   timestamptz,
  status            varchar(10) not null default 'uploaded' check (status in ('uploaded','done')),
  created_at        timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- report_sends（月次出席レポート送信ログ）
-- ----------------------------------------------------------------------------
create table report_sends (
  id            integer generated by default as identity primary key,
  student_id    integer not null references students(id) on delete cascade,
  report_year   integer not null,
  report_month  integer not null,
  send_method   varchar(10) not null check (send_method in ('email','fax')),
  sent_to       varchar(200),
  memo          text,
  sent_at       timestamptz default now()
);

-- ----------------------------------------------------------------------------
-- messages / message_reads / message_replies（保護者向け連絡）
-- ----------------------------------------------------------------------------
create table messages (
  id            integer generated by default as identity primary key,
  academy_id    integer not null default 1 references academies(id),
  title         varchar(200) not null,
  body          text not null,
  image_path    varchar(300),
  target_type   varchar(10) not null default 'all' check (target_type in ('all','department','student')),
  target_dept   varchar(10) check (target_dept in ('小中等部','高等部')),
  target_sid    integer references students(id) on delete set null,
  is_published  boolean not null default false,
  published_at  timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create trigger trg_messages_updated_at before update on messages
  for each row execute function set_updated_at();

create table message_reads (
  id          integer generated by default as identity primary key,
  message_id  integer not null references messages(id) on delete cascade,
  student_id  integer not null references students(id) on delete cascade,
  read_at     timestamptz default now(),
  unique (message_id, student_id)
);

create table message_replies (
  id                integer generated by default as identity primary key,
  message_id        integer not null references messages(id) on delete cascade,
  student_id        integer not null references students(id) on delete cascade,
  body              text not null,
  is_read_by_admin  boolean not null default false,
  created_at        timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- todo_items / todo_checks（やることリスト）
-- ----------------------------------------------------------------------------
create table todo_items (
  id           integer generated by default as identity primary key,
  academy_id   integer not null default 1 references academies(id),
  target_type  varchar(10) not null default 'student' check (target_type in ('all','department','student')),
  target_dept  varchar(10) check (target_dept in ('小中等部','高等部')),
  target_sid   integer references students(id) on delete cascade,
  title        varchar(200) not null,
  content      text,
  item_type    varchar(10) not null default 'task' check (item_type in ('text','link','task')),
  link_url     varchar(500),
  due_date     date,
  sort_order   integer not null default 0,
  is_active    boolean not null default true,
  created_at   timestamptz not null default now()
);

create table todo_checks (
  id          integer generated by default as identity primary key,
  todo_id     integer not null references todo_items(id) on delete cascade,
  student_id  integer not null references students(id) on delete cascade,
  checked_at  timestamptz default now(),
  unique (todo_id, student_id)
);

-- ----------------------------------------------------------------------------
-- sns_goals / sns_goal_posts（SNS投稿ネタツール）
-- ----------------------------------------------------------------------------
create table sns_goals (
  id             integer generated by default as identity primary key,
  academy_id     integer references academies(id),
  theme          varchar(255) not null,
  target_count   integer not null,
  duration_days  integer not null,
  start_date     date not null,
  end_date       date not null,
  status         varchar(15) not null default 'active'
                   check (status in ('active','achieved','not_achieved','cancelled')),
  actual_count   integer,
  checked_at     timestamptz,
  created_by     integer references admin_users(id),
  created_at     timestamptz not null default now()
);

create table sns_goal_posts (
  id          integer generated by default as identity primary key,
  goal_id     integer not null references sns_goals(id) on delete cascade,
  day_offset  integer not null,
  platform    varchar(30) not null,
  post_type   varchar(150) not null,
  body        text not null,
  created_at  timestamptz not null default now(),
  unique (goal_id, day_offset)
);

-- ----------------------------------------------------------------------------
-- operation_logs（操作履歴）
-- ----------------------------------------------------------------------------
create table operation_logs (
  id           integer generated by default as identity primary key,
  academy_id   integer references academies(id),
  admin_id     integer references admin_users(id),
  admin_name   varchar(100),
  action       varchar(100) not null,
  target_type  varchar(50),
  target_id    integer,
  detail       text,
  ip_address   varchar(45),
  created_at   timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- system_settings（KVS。APIキー等は値をここに直接コミットしない運用）
-- ----------------------------------------------------------------------------
create table system_settings (
  setting_key    varchar(50) primary key,
  setting_value  text,
  updated_at     timestamptz not null default now()
);
create trigger trg_system_settings_updated_at before update on system_settings
  for each row execute function set_updated_at();

-- ============================================================================
-- Row Level Security
-- ============================================================================
-- 現段階（Phase 1 MVP）では「ログイン済みユーザーのみアクセス可」までを担保する。
-- 学院ごとのデータ分離（academy_idでのスコープ）はPhase 4で admin_users.academy_id と
-- auth.uid() を突き合わせるポリシーに強化すること。それまでは匿名アクセスの遮断のみ。

do $$
declare
  t text;
begin
  for t in
    select unnest(array[
      'academies','admin_users','schools','students','attendance','calendar_events',
      'worksheet_files','assignments','assignment_scores','student_subject_levels',
      'weak_points','learning_progress','hs_reports','report_sends',
      'messages','message_reads','message_replies','todo_items','todo_checks',
      'sns_goals','sns_goal_posts','operation_logs','system_settings'
    ])
  loop
    execute format('alter table %I enable row level security', t);
    execute format(
      'create policy %I on %I for all to authenticated using (true) with check (true)',
      t || '_authenticated_all', t
    );
  end loop;
end $$;
