-- ============================================================================
-- 保護者向け日次レポート（v2ロードマップ B）
-- ============================================================================
-- 「今日何をやったか」を保護者に見せる日次レポート。
-- auto_summary はアプリ側で出欠・学習進捗・カレンダーの当日情報から組み立てて
-- 保存する（都度リアルタイム集計ではなく、生成時点のスナップショットとして残す）。
-- 指導（guidance）を行った場合はチェックし、その内容も保護者に共有する。

create table daily_reports (
  id              integer generated by default as identity primary key,
  student_id      integer not null references students(id) on delete cascade,
  report_date     date not null,
  auto_summary    text,
  staff_note      text,
  guidance_given  boolean not null default false,
  guidance_note   text,
  created_by      integer references admin_users(id),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (student_id, report_date)
);
create trigger trg_daily_reports_updated_at before update on daily_reports
  for each row execute function set_updated_at();

alter table daily_reports enable row level security;
create policy daily_reports_authenticated_all on daily_reports
  for all to authenticated using (true) with check (true);

-- カレンダーの「イレギュラーな出来事」記録用カテゴリを追加
alter table calendar_events drop constraint calendar_events_event_category_check;
alter table calendar_events add constraint calendar_events_event_category_check
  check (event_category in ('休校日','行事','定期テスト','長期休暇','お知らせ','イレギュラー','その他'));

-- ----------------------------------------------------------------------------
-- 保護者マイページ用: トークン一致の生徒本人の日次レポートのみ返すRPC
-- ----------------------------------------------------------------------------
create or replace function get_daily_reports_by_mypage_token(p_token text, p_limit int default 14)
returns table (
  report_date date,
  auto_summary text,
  staff_note text,
  guidance_given boolean,
  guidance_note text
)
language sql
security definer
set search_path = public
as $$
  select dr.report_date, dr.auto_summary, dr.staff_note, dr.guidance_given, dr.guidance_note
  from daily_reports dr
  join students s on s.id = dr.student_id
  where s.mypage_token = p_token
  order by dr.report_date desc
  limit p_limit
$$;

grant execute on function get_daily_reports_by_mypage_token(text, int) to anon, authenticated;
